pcaversaccio/snekmate

src/utils/Create2Address.vy, src/utils/CreateAddress.vy
in vyper, `convert` is a checked downcast. therefore we need to clean
the upper bits before calling `convert`
=> fix conversion util

README.md, package.json, src/tokens/ERC20.vy, src/tokens/ERC721.vy, src/utils/Create2Address.vy, src/utils/CreateAddress.vy, src/utils/EIP712DomainSeparator.vy, src/utils/Multicall.vy, yarn.lock
This PR implements the `ERC-20` token standard in Vyper. Also, it adds a basic draft version (=placeholder) of the `ERC-721` token standard. The final `ERC-721` implementation will be however part of a future PR.
=> 👻 `ERC-20` Implementation

src/utils/SignatureChecker.vy, test/utils/SignatureChecker.t.sol
=> 🧠 Return `False` Instead of Reverting in `SignatureChecker`

src/utils/Create2Address.vy, src/utils/CreateAddress.vy, src/utils/EIP712DomainSeparator.vy
We use the convention `I` & `ContractName` as interface names for in-contract interfaces.
=> 🥢 Make In-Contract Interface Names Consistent

package.json, yarn.lock
=> 🔁 Bump `ethers` From `6.0.8` to `6.1.0`

package.json, yarn.lock
This PR bumps the following dependencies:
- `ethers` from `6.2.0` to `6.2.2`, and
- `prettier` from `2.8.6` to `2.8.7`.
We also bump the `forge-std` submodule to the latest available commit.
=> 🔁 Bump `ethers` and `prettier`

src/tokens/ERC1155.vy, src/tokens/interfaces/IERC1155MetadataURI.vy
As title. h/t goes to @jtriley-eth for raising this issue.
=> 📖 Add Remark on `\{id\}` Substring Handling in `_uri` Function of `ERC1155`

src/extensions/ERC4626.vy
As title. This addresses an `ape` compilation issue discovered [here](https://github.com/vyperlang/vyper/issues/3392).
=> 🥢 Use Relative Import for `IERC20Permit` in `ERC4626`

src/tokens/ERC1155.vy, src/tokens/interfaces/IERC1155MetadataURI.vy, test/tokens/ERC721.t.sol
As title (fixes https://github.com/foundry-rs/foundry/issues/4940). Furthermore, I remove the deprecated Vyper escape sequence `\` (introduced via PR https://github.com/pcaversaccio/snekmate/pull/109) in order to remove any `forge` compilation warnings.
=> 🐛 Fix Non-Reverting Fuzz Test in `ERC721.t.sol`

.github/workflows/checks.yml, .solhint.json, package.json, test/tokens/mocks/ERC1155ReceiverMock.sol, test/tokens/mocks/ERC721ReceiverMock.sol, test/utils/Math.t.sol, yarn.lock
This PR bumps `solhint` version to `3.6.1` and `eslint` version to `8.47.0`. Accordingly, I adjust the new `solhint` rules. Furthermore, I bump all submodules to the latest available commit.
=> 🔁 Bump `solhint` to Version `3.6.1` and `eslint` to Version `8.47.0`

.github/workflows/publish-pypi.yml, .github/workflows/publish-test-pypi.yml, CHANGELOG.md, package.json, pnpm-lock.yaml, pyproject.toml, scripts/build.py
This PR refactors how the binary wheel and source tarball are built. Before this change, the wheel folder structure looked like this:
```ml
snekmate-0.0.X-py3-none-any.whl
├── auth
├── extensions
├── governance
├── tokens
└── utils
```
After this PR, it will look like this:
```ml
snekmate-0.0.X-py3-none-any.whl
└── snekmate
├── auth
├── extensions
├── governance
├── tokens
└── utils
```
You can test the build via:
```console
pip install -i https://test.pypi.org/simple/ snekmate==0.0.5rc2 -t .
```
A CI test run that publishes to TestPyPI is available [here](https://github.com/pcaversaccio/snekmate/actions/runs/7837793885).
=> 👷 Implement `snekmate`-Namespaced Distribution Package Building

src/snekmate/utils/MerkleProofVerification.vy
Similarly to #82, the `MerkleProofVerification` functions will run out of gas (with the default gas limits) if the maximum array size (currently set to `max_value(uint16)`) is not adjusted accordingly.
=> 📖 Add Note on Memory Usage of Dynamic Arrays in `MerkleProofVerification` Contract

src/snekmate/utils/Math.vy
Revise the comment in `wad_exp` from `< 0.5` to `< 1` to ensure consistency with the implementation.
=> 📖 Fix Comment in `wad_exp`

test/governance/TimelockController.t.sol
The `foundry` PR https://github.com/foundry-rs/foundry/pull/7819 removes the `preserve_state` config and commits calls by default (i.e. `timestamp` changes will be reflected in the test contract after each call). This new change breaks the invariant `invariantExecutingNotReadyProposal` since calls within invariant runs to the function `TimelockControllerHandler.execute`, which uses `vm.warp(block.timestamp + minDelay);`, will advance the underlying `block.timestamp` of the test contract itself (reverting calls will be treated like a normal call; exactly how it works on-chain right now) and thus can break the assertions in `invariantExecutingNotReadyProposal`. To fix this, we reset the `timestamp` within the invariant `invariantExecutingNotReadyProposal` to the initial `timestamp` of the …
=> ♻️ Reset `timestamp` in `invariantExecutingNotReadyProposal` Test

.github/workflows/halmos.yml
Replace the Homebrew-based Yices 2 SMT solver installation in the `halmos` CI pipeline with `apt-get` (i.e. pulling directly the binaries). This will speed up the installation considerably (Homebrew installs the Yices 2 SMT solver from the source).
=> 👷 Use `apt-get`-Based Binaries for Yices 2 SMT Solver

src/snekmate/utils/merkle_proof_verification.vy, src/snekmate/utils/mocks/merkle_proof_verification_mock.vy
It's important to highlight that the condition where `((len(proof) == 1) and (len(leaves) == 0))` (i.e. the empty set), is effectively treated as a no-op in `_process_multi_proof` and thus is considered a valid multiproof, returning `proof[0]`.
=> 📖 Add Comment on Empty Set in Merkle Multiproof

.github/workflows/halmos.yml, CHANGELOG.md, test/halmos.toml, test/tokens/halmos/ERC1155TestHalmos.t.sol, test/tokens/halmos/ERC20TestHalmos.t.sol, test/tokens/halmos/ERC721TestHalmos.t.sol, test/utils/halmos/MathTestHalmos.t.sol
[`halmos`](https://github.com/a16z/halmos) has released support for the following new cheat codes via PRs [#360](https://github.com/a16z/halmos/pull/360) and (small patch) [#364](https://github.com/a16z/halmos/pull/364):
```solidity
createCalldata(string contractName);
createCalldata(string contractName, bool includeViewFunctions);
createCalldata(string filename, string contractName);
createCalldata(string filename, string contractName, bool includeViewFunctions);
```
> Please note that `includeViewFunctions` defaults to `false`, if not provided.
This PR refactors the `halmos`-based tests to capitalise on these new cheat codes. To verify the correct behaviour of the Vyper compiler for `view` and `pure` functions, we include read-only functions in the calldata creation.
=> ♻️ Use Native `halmos` `createCalldata` Cheat Code

CHANGELOG.md, foundry.toml, package.json, pnpm-lock.yaml, test/tokens/echidna/ERC20Properties.sol, test/tokens/echidna/ERC721Properties.sol
This PR updates the 🐍 snekmate's `echidna`-based tests to match the new `cancun` EVM support introduced in `echidna` [`v2.2.5`](https://github.com/crytic/echidna/releases/tag/v2.2.5). This ensures our tests remain compatible with the latest EVM version.
=> ♻️ Use `cancun` in `echidna`-Based Tests

.github/workflows/checks.yml, .github/workflows/halmos-venom.yml, .github/workflows/halmos.yml, .github/workflows/publish-pypi.yml, .github/workflows/publish-test-pypi.yml, .github/workflows/test-contracts-venom.yml, .github/workflows/test-contracts.yml, CONTRIBUTING.md, README.md
This PR upgrades [Python](https://www.python.org) to the latest [`3.13`](https://docs.python.org/3/whatsnew/3.13.html) release in the CI pipelines. In addition, the contribution guidelines are amended to include Python as a required dependency.
=> 👷‍♂️ Update Python to Version `3.13`

README.md
This PR fixes two broken links in the [`README` test section](https://github.com/pcaversaccio/snekmate?#%EF%B8%8F-tests) that point to `ERC20.vy` and `ERC721.vy` 🐍Vyper contract files. The issue is due to case sensitivity, as the actual repository structure uses lowercase `erc20.vy` and `erc721.vy`.
=> 📖 Fix Broken `erc20`/`erc721` Links in `README`

src/snekmate/utils/p256.vy
This PR documents the requirement for the [`MODEXP`](https://www.evm.codes/precompiled?fork=cancun#0x05) precompiled contract, as specified by [EIP-198](https://eips.ethereum.org/EIPS/eip-198) and introduced in the Byzantium hard fork, for the `p256` contract.
=> 📖 Document `MODEXP` Requirement in `p256`
