pcaversaccio/snekmate

.github/workflows/test-contracts.yml
---
Closes https://github.com/foundry-rs/foundry/issues/3394
=> ci: run forge snapshot with NO_COLOR=1

src/tokens/ERC20.vy
=> ✔️ implement feedback from Charles

README.md, package.json, src/tokens/ERC20.vy, src/tokens/ERC721.vy, src/tokens/interfaces/IERC721Enumerable.vy, src/tokens/interfaces/IERC721Metadata.vy, src/tokens/interfaces/IERC721Permit.vy, src/tokens/interfaces/IERC721Receiver.vy, src/utils/EIP712DomainSeparator.vy, yarn.lock
=> 🫡 ERC-721 Token Implementation

CONTRIBUTING.md, README.md
This PR adds the official "Contributing Guidelines" of 🐍 Snekmate.
=> ✒️ Contributing Guidelines

src/tokens/ERC721.vy
Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>
---
Discussion thread #40
=> `ERC721`: Use local variable in `safe_mint` function to increment state variable (gas optimisation)

test/tokens/ERC1155.t.sol, test/tokens/interfaces/IERC1155Extended.sol, test/tokens/mocks/ERC1155InvalidReceiverMock.sol, test/tokens/mocks/ERC1155NonReceiverMock.sol, test/tokens/mocks/ERC1155ReceiverMock.sol
---
Adds unit tests to ERC1155. Includes each function and branch, also includes tests to assert compliance with [EIP-1155](https://eips.ethereum.org/EIPS/eip-1155).
=> ✨ ERC-1155 Unit Tests and Mocks

test/tokens/interfaces/IERC1155Extended.sol, test/utils/interfaces/IBase64.sol, test/utils/interfaces/IBatchDistributor.sol, test/utils/interfaces/IECDSA.sol, test/utils/interfaces/IMerkleProofVerification.sol, test/utils/interfaces/IMulticall.sol, test/utils/interfaces/ISignatureChecker.sol
=> 🦹🏼‍♂Change `memory` to `calldata` in Solidity Test Interfaces

CHANGELOG.md
=> 🕓 Add `CHANGELOG`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md, CONTRIBUTING.md, GUIDELINES.md, README.md, src/tokens/ERC20.vy
=> 📖 Add Official Snekmate Style Guide

lib/utils/VyperDeployer.sol, src/utils/CreateAddress.vy, test/tokens/ERC20.t.sol, test/utils/Create2Address.t.sol, test/utils/CreateAddress.t.sol, test/utils/ECDSA.t.sol, test/utils/mocks/MockCallee.sol
- Fuzz tests for [`CreateAddress`](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/CreateAddress.vy)
- Fuzz tests for [`Create2Address`](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/Create2Address.vy)
=> 💥 Implement Fuzz Tests for `CreateAddress` and `Create2Address`

package.json, yarn.lock
=> 🔁 Bump `eslint` From `8.33.0` to `8.34.0` and Pull Latest Submodule Versions

src/tokens/ERC721.vy, src/tokens/interfaces/IERC4906.vy, test/tokens/ERC721.t.sol
=> 💥 Add `IERC4906` Support to ERC-721

package.json, yarn.lock
=> 🔁 Bump `@openzeppelin/merkle-tree` From `1.0.2` to `1.0.3`

package.json, yarn.lock
As title. Furthermore, we also bump all submodules to the latest available commits.
=> 🔁 Bump `ethers` From `6.2.2` to `6.2.3`

package.json, yarn.lock
As title. Furthermore, we also bump all submodules to the latest available commits.
=> 🔁 Bump `eslint` From `8.36.0` to `8.37.0`

package.json, yarn.lock
As title. Furthermore, we also bump all submodules to the latest available commits.
=> 🔁 Bump `eslint` From `8.37.0` to `8.39.0`

.github/pull_request_template.md
=> 🥢 Enhance PR Template

CHANGELOG.md, src/auth/AccessControl.vy, src/auth/Ownable.vy, src/auth/Ownable2Step.vy, src/auth/interfaces/IAccessControl.vy, src/extensions/ERC4626.vy, src/tokens/ERC1155.vy, src/tokens/ERC20.vy, src/tokens/ERC721.vy, src/tokens/interfaces/IERC1155.vy, src/tokens/interfaces/IERC1155MetadataURI.vy, src/tokens/interfaces/IERC1155Receiver.vy, src/tokens/interfaces/IERC20Permit.vy, src/tokens/interfaces/IERC4906.vy, src/tokens/interfaces/IERC721Enumerable.vy, src/tokens/interfaces/IERC721Metadata.vy, src/tokens/interfaces/IERC721Permit.vy, src/tokens/interfaces/IERC721Receiver.vy, src/utils/Base64.vy, src/utils/BatchDistributor.vy, src/utils/Create2Address.vy, src/utils/CreateAddress.vy, src/utils/ECDSA.vy, src/utils/EIP712DomainSeparator.vy, src/utils/Math.vy, src/utils/MerkleProofVerification.vy, src/utils/Multicall.vy, src/utils/SignatureChecker.vy
As title. Fixes https://github.com/pcaversaccio/snekmate/issues/119.
=> ♻️ Add NatSpec Field `@custom:contract-name`

CHANGELOG.md, src/extensions/ERC4626.vy, src/tokens/ERC20.vy, src/tokens/ERC721.vy
=> ♻️ Fix `implements` Interfaces `ERC20Detailed`, `IERC721Metadata`, and `ERC4626`

package.json, pyproject.toml
This PR bumps the version of 🐍 snekmate to `0.0.2`.
=> 💥 Bump Release Version to `0.0.2`

.github/workflows/checks.yml
This PR adds [`awesome_bot`](https://github.com/dkhamsing/awesome_bot/tree/master) to the CI pipeline for URL checking.
=> 👷‍♂️ Add `awesome_bot` to CI Pipeline

src/tokens/ERC1155.vy, src/tokens/ERC721.vy, src/tokens/interfaces/IERC1155.vy
As title. Inspired by https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4283.
=> 📖 Add Code Comments in `IERC1155`, `ERC1155`, and `ERC721` on Potential Reentrancy Risk

package.json, yarn.lock
=> 🔁 Bump `ethers` From `6.6.1` to `6.6.2`

.prettierrc.yml, package.json, test/utils/scripts/generate-bad-multiproof-leaves.js, test/utils/scripts/generate-bad-multiproof-proof-flags.js, test/utils/scripts/generate-bad-multiproof.js, test/utils/scripts/generate-bad-proof.js, test/utils/scripts/generate-leaf.js, test/utils/scripts/generate-multiproof-leaves.js, test/utils/scripts/generate-multiproof-proof-flags.js, test/utils/scripts/generate-multiproof.js, test/utils/scripts/generate-no-such-leaf.js, test/utils/scripts/generate-proof-no-such-leaf.js, test/utils/scripts/generate-proof.js, test/utils/scripts/generate-root.js, yarn.lock
As title. Note that the plugin automatic search feature has been removed from `prettier` (see [here](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker)) so it has to be declared in the config file `.prettierrc.yml` from now on:
```yml
plugins:
- "prettier-plugin-solidity"
``` 
h/t to @Janther for his investigation [here](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/881).
=> 🔁 Bump `prettier` to Version `3.0.0`

package.json, yarn.lock
=> 🔁 Bump `eslint` From `8.44.0` to `8.45.0`

package.json, yarn.lock
=> 🔁 Bump Submodules

package.json, yarn.lock
=> 🔁 Bump `eslint` From `8.47.0` to `8.48.0`

README.md
=> 📖 Add 🐍 snekmate Image to `README`

.github/workflows/publish-pypi.yml, .github/workflows/publish-test-pypi.yml
As title. Also, see [here](https://docs.pypi.org/trusted-publishers) for how the setup works.
=> 👷‍♂️ Publishing to `PyPI` and `TestPyPI` with a Trusted Publisher

.github/workflows/checks.yml, .github/workflows/publish-npm.yml, .github/workflows/publish-pypi.yml, .github/workflows/publish-test-pypi.yml, .github/workflows/test-contracts.yml
As title. Furthermore, I add, for general convenience, to all CI actions a `workflow_dispatch` trigger.
=> 👷‍♂️ Use `environment` in CI Publish Actions

CHANGELOG.md, package.json, pyproject.toml, test/halmos.toml
██╗░░░██╗██╗░░░██╗██████╗░███████╗██████╗░
██║░░░██║╚██╗░██╔╝██╔══██╗██╔════╝██╔══██╗
╚██╗░██╔╝░╚████╔╝░██████╔╝█████╗░░██████╔╝
░╚████╔╝░░░╚██╔╝░░██╔═══╝░██╔══╝░░██╔══██╗
░░╚██╔╝░░░░░██║░░░██║░░░░░███████╗██║░░██║
░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░░░╚══════╝╚═╝░░╚═╝
███████╗██╗░░░██╗░█████╗░██╗░░██╗██╗███╗░░██╗░██████╗░
██╔════╝██║░░░██║██╔══██╗██║░██╔╝██║████╗░██║██╔════╝░
█████╗░░██║░░░██║██║░░╚═╝█████═╝░██║██╔██╗██║██║░░██╗░
██╔══╝░░██║░░░██║██║░░██╗██╔═██╗░██║██║╚████║██║░░╚██╗
██║░░░░░╚██████╔╝╚█████╔╝██║░╚██╗██║██║░╚███║╚██████╔╝
╚═╝░░░░░░╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░
██████╗░░█████╗░░█████╗░██╗░░██╗░██████╗██╗
██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██║
██████╔╝██║░░██║██║░░╚═╝█████═╝░╚█████╗░██║
██╔══██╗██║░░██║██║░░██╗██╔═██╗░░╚═══██╗╚═╝ …
=> 💥 Release `🐍 snekmate` `0.1.0`

.gas-snapshot, .gas-snapshot-venom
This PR updates the `.gas-snapshot` and `.gas-snapshot-venom` files to align with the latest Vyper `master` commit [`dd5a3d9e0f1e8685cd2b41ba23cbb4c3dfcff784`](https://github.com/vyperlang/vyper/commit/dd5a3d9e0f1e8685cd2b41ba23cbb4c3dfcff784).
=> ♻️ Update `.gas-snapshot` and `.gas-snapshot-venom`

.github/workflows/publish-npm.yml
This PR adds the generation of a provenance statement whenever `🐍 snekmate` is published via the CI pipeline to the [`npm` registry](https://www.npmjs.com/package/snekmate). Also, see https://github.com/pnpm/pnpm/issues/6435 and https://github.com/pnpm/pnpm/pull/6436.
=> 👷 Add Provenance to `npm` Release

CHANGELOG.md, package.json, pnpm-lock.yaml, pyproject.toml
███████╗███╗░░░██╗███████╗██╗░░██╗███╗░░░███╗░█████╗░████████╗███████╗
██╔════╝████╗░░██║██╔════╝██║░██╔╝████╗░████║██╔══██╗╚══██╔══╝██╔════╝
███████╗██╔██╗░██║█████╗░░█████╔╝░██╔████╔██║███████║░░░██║░░░█████╗░░
╚════██║██║╚██╗██║██╔══╝░░██╔═██╗░██║╚██╔╝██║██╔══██║░░░██║░░░██╔══╝░░
███████║██║░╚████║███████╗██║░░██╗██║░╚═╝░██║██║░░██║░░░██║░░░███████╗
╚══════╝╚═╝░░╚═══╝╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝
░██████╗░░░░██╗░░░██████╗░
██╔═████╗░░███║░░░╚════██╗
██║██╔██║░░╚██║░░░░█████╔╝
████╔╝██║░░░██║░░░██╔═══╝░
╚██████╔╝██╗██║██╗███████╗
░╚═════╝░╚═╝╚═╝╚═╝╚══════╝
This PR drops the `🐍 snekmate` `0.1.2` release, targeting the latest Vyper version [`0.4.3`](https://github.com/vyperlang/vyper/releases/tag/v0.4.3).
> [!IMPORTANT]
> This release will make all 🐍 snekmate …
=> 💥 Release `🐍 snekmate` `0.1.2`
